services:

  mydb:
    image: postgres
    restart: always
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: names
  worker:
    image: pauulosergio/python_worker:1.3
    ports:
    - 5000:5000
  s_database:
    image: pauulosergio/s_database:1.7
    depends_on:
      mydb:
        condition: service_healthy
    ports:
    - "3030:3030"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080